import { mkdirSync } from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import {
  drizzle,
  type BetterSQLite3Database,
} from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { env } from "@/lib/env";
import * as schema from "./schema";

export type Db = BetterSQLite3Database<typeof schema> & {
  readonly $client: Database.Database;
};

/** Generated by `drizzle-kit generate`; ships beside the server in the Docker image. */
const MIGRATIONS_FOLDER = path.join(process.cwd(), "drizzle");
const DB_FILENAME = "auditor.db";
const BUSY_TIMEOUT_MS = 5000;

/**
 * Opens SQLite with WAL and foreign keys on (SQLite leaves them off per connection), then
 * applies every pending migration. Pass `:memory:` for tests. A failed migration throws: a bug.
 */
export const openDb = (filename: string): Db => {
  const sqlite = new Database(filename);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");
  sqlite.pragma(`busy_timeout = ${BUSY_TIMEOUT_MS}`);
  const db = drizzle(sqlite, { schema });
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return db;
};

const openAppDb = (): Db => {
  mkdirSync(env.DATA_DIR, { recursive: true });
  return openDb(path.join(env.DATA_DIR, DB_FILENAME));
};

const memo = <T>(make: () => T): (() => T) => {
  let value: T | undefined;
  return () => (value ??= make());
};

/** The app's one connection to `$DATA_DIR/auditor.db`, opened and migrated on first use. */
export const getDb: () => Db = memo(openAppDb);
